# Generated by Django 3.1.1 on 2020-11-10 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20201027_1813'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ('first_name',)},
        ),
    ]
