# Generated by Django 3.1.1 on 2020-09-18 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unlike',
            name='post',
        ),
        migrations.RemoveField(
            model_name='unlike',
            name='profile',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.DeleteModel(
            name='Unlike',
        ),
    ]
