# Generated by Django 3.1.1 on 2020-11-10 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20201029_1118'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feed',
        ),
    ]
