# Generated by Django 3.1.1 on 2020-11-10 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20201110_0817'),
        ('post', '0004_delete_feed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('from_prof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_profile', to='profiles.profile')),
                ('to_prof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_profile', to='profiles.profile')),
            ],
        ),
    ]
