# Generated by Django 3.1 on 2020-09-16 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20200916_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment',
            field=models.TextField(default=True, max_length=300),
            preserve_default=False,
        ),
    ]
